import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-white text-gray-900 px-[20px] md:px-8 lg:px-[120px]">
        <Header />
        <main className="pt-16">{children}</main>
        {/* Footer will go here later */}
      </body>
    </html>
  );
}
