import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/Header";
import Providers from "./providers";
import Footer from "@/components/layout/footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-white text-gray-900 ">
        <Providers>
          <Header />
          <main className="pt-16 px-[20px] md:px-8 lg:px-[120px]">
            {children}
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
